MAX_ELEMENT_NAME_NAME = 50
MAX_ELEMENT_SYMBOL_LEN = 10
MAX_GRADE_NAME_LEN = 128
MAX_GRADE_CODE_LEN = 50


TC_RATE_DIGITS = 5
TC_RATE_DECIMAL_PLACES = 3
TC_MIN_ELE_RATE = 0
TC_MAX_ELE_RATE = 100

FK_GRADE_TO_TC = "grade_tc"
FK_ELE_TO_TC = "ele_tc"
