# Generated by Django 4.2.4 on 2023-11-15 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import grades.models.ElementModels.modelvalidators
import grades.models.GradeModels.modelvalidators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            grades.models.ElementModels.modelvalidators.EleNameValidator
                        ],
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        max_length=10,
                        validators=[
                            grades.models.ElementModels.modelvalidators.EleSymbolValidator
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        validators=[
                            grades.models.GradeModels.modelvalidators.GradeCodeValidator
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TargetChemistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "relaxed_min_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "relaxed_max_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ele_tc",
                        to="grades.element",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_tc",
                        to="grades.grade",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["code"], name="grades_grad_code_b2aa67_idx"),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("code",), name="grade_code_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="element",
            index=models.Index(fields=["symbol"], name="grades_elem_symbol_c678b3_idx"),
        ),
        migrations.AddConstraint(
            model_name="element",
            constraint=models.UniqueConstraint(
                fields=("symbol",), name="ele_symbol_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="targetchemistry",
            index=models.Index(fields=["grade"], name="grades_targ_grade_i_98c24f_idx"),
        ),
        migrations.AddIndex(
            model_name="targetchemistry",
            index=models.Index(
                fields=["element"], name="grades_targ_element_1b5162_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="targetchemistry",
            constraint=models.UniqueConstraint(
                fields=("grade", "element"), name="grade_ele_unique_in_tc"
            ),
        ),
    ]
